services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root-user
      POSTGRES_PASSWORD: password123!
      PGPASSWORD: password123!
    healthcheck:
      test: ['CMD', '/health-check.sh', 'postgres', 'root-user', 'password123!']
      interval: 15s
      timeout: 10s
      retries: 20
    ports:
      - '15432:5432'
    tty: true
    volumes:
      - ./db/health-check.sh:/health-check.sh
      - ./db/postgresql.conf:/etc/postgresql.conf
    tmpfs:
      - /var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    tty: true
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/mobile/node_modules
      - /usr/src/app/services/api/node_modules
      - /usr/src/app/shared/settings/node_modules
      - /usr/src/app/web/node_modules
    environment:
      UV_THREADPOOL_SIZE: 128
      NODE_ENV: production
      LOG_LEVEL: info
      PORT: 3000
      PG_CONNECTION: postgres://root-user:password123!@db:5432/postgres
    working_dir: /usr/src/app
    command: ['node', '--watch-path=./services/api', '--watch-path=./shared', 'services/api/service.js']
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '4000:4000'
    tty: true
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/mobile/node_modules
      - /usr/src/app/services/api/node_modules
      - /usr/src/app/shared/settings/node_modules
      - /usr/src/app/web/node_modules
    environment:
      UV_THREADPOOL_SIZE: 128
      NODE_ENV: production
      LOG_LEVEL: info
      PORT: 4000
    working_dir: /usr/src/app/web
    command: ['npm', 'run', 'dev']
  mobile:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '8081:8081'
    tty: true
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/mobile/node_modules
      - /usr/src/app/services/api/node_modules
      - /usr/src/app/shared/settings/node_modules
      - /usr/src/app/web/node_modules
    environment:
      UV_THREADPOOL_SIZE: 128
      NODE_ENV: production
      LOG_LEVEL: info
      EXPO_DEVTOOLS_LISTEN_ADDRESS: 0.0.0.0
    working_dir: /usr/src/app/mobile
    command: ['npm', 'start']
